name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create release for"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Create RBZ file
        run: |
          # Create a temporary directory
          mkdir -p temp_plugin

          # Copy the plugin files
          cp -r csv_extension temp_plugin/
          cp csv_extension_loader.rb temp_plugin/

          # Create the RBZ file
          cd temp_plugin
          zip -r ../rasgo_csv.rbz *
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name || inputs.tag }}
          files: |
            rasgo_csv.rbz
            csv_extension_loader.rb
            csv_extension/**/*.rb
          draft: false
          prerelease: false
          generate_release_notes: true
